# The Ubuntu based image is ~890MB
# This Alpine based image is ~665MB

FROM  python:alpine3.7
LABEL maintainer=jon@jaggersoft.com

RUN apk --no-cache add openblas-dev

RUN apk add --no-cache --virtual .build-deps \
  musl-dev linux-headers g++ \
  && pip install datetime \
  && pip install numpy \
  && pip install scipy \
  && pip install panda \
  && pip install pep8 \
  && apk del .build-deps

RUN python --version | grep -q 3.6.4