FROM python
LABEL maintainer=jon@jaggersoft.com

RUN apt-get update \
 && pip3 install --upgrade pip numpy scipy panda datetime pycodestyle

COPY usercustomize.py /usr/local/lib/python3.6/site-packages
